[project]
name = "org-sage"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "langchain>=1.2.0",
    "orgparse>=0.4.20251020",
    "pandas>=2.3.3",
    "python-dotenv>=1.2.1",
]
